# Generated by Django 5.2.8 on 2026-01-30 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=100, unique=True, verbose_name='Session key')),
                ('access_token', models.TextField(verbose_name='Access token')),
                ('refresh_token', models.TextField(blank=True, null=True, verbose_name='Refresh token')),
                ('token_type', models.CharField(default='Bearer', max_length=50, verbose_name='Token turi')),
                ('expires_at', models.DateTimeField(verbose_name='Token muddati')),
                ('user_agent', models.TextField(blank=True, verbose_name='User agent')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP manzil')),
                ('device_info', models.JSONField(blank=True, default=dict, verbose_name="Device ma'lumotlari")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='Oxirgi faollik')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='student.student', verbose_name='Talaba')),
            ],
            options={
                'verbose_name': 'User Session',
                'verbose_name_plural': 'User Sessions',
                'ordering': ['-last_activity'],
            },
        ),
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(auto_now_add=True, verbose_name='Login vaqti')),
                ('logout_time', models.DateTimeField(blank=True, null=True, verbose_name='Logout vaqti')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP manzil')),
                ('user_agent', models.TextField(verbose_name='User agent')),
                ('device_type', models.CharField(blank=True, max_length=50, verbose_name='Device turi')),
                ('success', models.BooleanField(default=True, verbose_name='Muvaffaqiyatli')),
                ('failure_reason', models.TextField(blank=True, verbose_name='Xatolik sababi')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to='student.student', verbose_name='Talaba')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserSession.usersession', verbose_name='Session')),
            ],
            options={
                'verbose_name': 'Login Tarixi',
                'verbose_name_plural': 'Login Tarixi',
                'ordering': ['-login_time'],
            },
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['student', '-last_activity'], name='UserSession_student_913d01_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['session_key'], name='UserSession_session_3ff5bc_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['expires_at'], name='UserSession_expires_a05b38_idx'),
        ),
        migrations.AddIndex(
            model_name='loginhistory',
            index=models.Index(fields=['student', '-login_time'], name='UserSession_student_8caa1b_idx'),
        ),
    ]
