# Generated by Django 5.2.8 on 2026-02-02 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserSession', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginhistory',
            name='device_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='Device turi'),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='token_type',
            field=models.CharField(default='Bearer', max_length=100, verbose_name='Token turi'),
        ),
    ]
