# Generated by Django 5.2.8 on 2026-02-03 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserSession', '0002_alter_loginhistory_device_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='session_key',
            field=models.CharField(max_length=255, unique=True, verbose_name='Session key'),
        ),
    ]
