# Generated by Django 5.2.8 on 2026-01-30 06:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='Savol matni')),
                ('score', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Ball')),
                ('order', models.IntegerField(default=0, verbose_name='Tartib raqami')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Savol',
                'verbose_name_plural': 'Savollar',
                'ordering': ['quiz', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=255, verbose_name='Javob varianti')),
                ('is_correct', models.BooleanField(default=False, verbose_name="To'g'ri javob")),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='main.question', verbose_name='Savol')),
            ],
            options={
                'verbose_name': 'Javob varianti',
                'verbose_name_plural': 'Javob variantlari',
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Test nomi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('time_limit', models.IntegerField(default=30, help_text='Daqiqalarda', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Vaqt chegarasi')),
                ('passing_score', models.IntegerField(default=60, help_text='Foizda', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name="O'tish bali")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_quizzes', to=settings.AUTH_USER_MODEL, verbose_name='Yaratuvchi')),
            ],
            options={
                'verbose_name': 'Test',
                'verbose_name_plural': 'Testlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(help_text="Format: Savol===Variant1===Variant2===#To'g'riVariant+++KeyingiSavol", verbose_name='Savol matni va javoblar')),
                ('score', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Ball')),
                ('is_processed', models.BooleanField(default=False, editable=False, verbose_name='Qayta ishlangan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_texts', to='main.quiz', verbose_name='Test')),
            ],
            options={
                'verbose_name': 'Savol yuklash (bulk)',
                'verbose_name_plural': 'Savollar yuklash (bulk)',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='main.quiz', verbose_name='Test'),
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'Jarayonda'), ('completed', 'Yakunlangan'), ('expired', 'Vaqti tugagan')], default='in_progress', max_length=20, verbose_name='Holat')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Boshlangan')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Tugatilgan')),
                ('time_taken', models.IntegerField(blank=True, help_text='Soniyalarda', null=True, verbose_name='Sarflangan vaqt')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='main.quiz', verbose_name='Test')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to='student.student', verbose_name='Talaba')),
            ],
            options={
                'verbose_name': 'Test urinishi',
                'verbose_name_plural': 'Test urinishlari',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_questions', models.IntegerField(verbose_name='Jami savollar')),
                ('correct_answers', models.IntegerField(verbose_name="To'g'ri javoblar")),
                ('wrong_answers', models.IntegerField(verbose_name="Noto'g'ri javoblar")),
                ('unanswered', models.IntegerField(default=0, verbose_name='Javobsiz')),
                ('total_score', models.IntegerField(verbose_name='Umumiy ball')),
                ('max_score', models.IntegerField(verbose_name='Maksimal ball')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Foiz')),
                ('passed', models.BooleanField(verbose_name="O'tdi")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='main.quizattempt', verbose_name='Urinish')),
            ],
            options={
                'verbose_name': 'Natija',
                'verbose_name_plural': 'Natijalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False, verbose_name="To'g'ri")),
                ('answered_at', models.DateTimeField(auto_now_add=True, verbose_name='Javob berilgan')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='main.quizattempt', verbose_name='Urinish')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.question', verbose_name='Savol')),
                ('selected_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.option', verbose_name='Tanlangan variant')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi javobi',
                'verbose_name_plural': 'Foydalanuvchi javoblari',
            },
        ),
        migrations.AddConstraint(
            model_name='quizattempt',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'in_progress')), fields=('student', 'quiz'), name='unique_active_attempt'),
        ),
        migrations.AddIndex(
            model_name='result',
            index=models.Index(fields=['passed', '-created_at'], name='main_result_passed_ba47ca_idx'),
        ),
        migrations.AddIndex(
            model_name='userresponse',
            index=models.Index(fields=['attempt', 'is_correct'], name='main_userre_attempt_3159ef_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userresponse',
            unique_together={('attempt', 'question')},
        ),
    ]
