# Generated by Django 5.2.8 on 2026-04-02 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_option_options_alter_result_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='attempts',
            field=models.IntegerField(default=1, verbose_name='Urinishlar soni'),
        ),
    ]
