# Generated by Django 5.2.8 on 2026-04-02 05:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_quizattempt_attempts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizattempt',
            name='attempts',
        ),
        migrations.AddField(
            model_name='quiz',
            name='attempt_limit',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Urinishlar soni (faqat standart testlar uchun)'),
        ),
    ]
