# Generated by Django 5.2.8 on 2026-04-02 07:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_quizattempt_attempts_quiz_attempt_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='attempt_limit',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Urinishlar soni'),
        ),
    ]
