# Generated by Django 5.2.8

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_quiz_attempt_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='expires_at',
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                null=True,
                verbose_name='Muddati tugash vaqti',
            ),
        ),
    ]
