# Generated by Django 5.2.8 on 2026-09-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_quizattempt_expires_at'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='psychologicalcategory',
            constraint=models.CheckConstraint(
                condition=models.Q(('min_score__lte', models.F('max_score'))),
                name='psych_category_min_lte_max',
            ),
        ),
    ]
