# Generated by Django 5.2.8 on 2026-01-26 11:50

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_name', models.CharField(blank=True, max_length=56, null=True, verbose_name='Talaba_Ismi')),
                ('phone_number', models.CharField(blank=True, max_length=56, null=True, verbose_name='Telfon-raqam')),
                ('student_imeg', models.ImageField(upload_to='media/', verbose_name='rasm')),
                ('student_id_number', models.CharField(blank=True, max_length=16, null=True, unique=True)),
                ('email', models.CharField(max_length=86)),
                ('passport_number', models.CharField(max_length=12, verbose_name='passport raqami')),
                ('birth_date', models.CharField(max_length=50, verbose_name="Tug'ilgan-kun-sanasi")),
                ('studentStatus', models.CharField(max_length=86, verbose_name='talaba-holati')),
                ('paymentForm', models.CharField(max_length=86, verbose_name="to'lov shakli")),
                ('faculty', models.CharField(max_length=86, verbose_name='fakultet')),
                ('level', models.CharField(max_length=86, verbose_name='kurs')),
                ('avg_gpa', models.CharField(max_length=86, verbose_name='Gpa-bali')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='StudentGirls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_of_birth', models.CharField(blank=True, max_length=100, null=True, verbose_name="Tug'ilgan joyi")),
                ('current_address', models.CharField(blank=True, max_length=256, null=True, verbose_name='Hozirgi manzili')),
                ('marital_status', models.CharField(choices=[('turmush_qurgan', 'Turmush qurgan'), ('turmush_qurmagan', 'Turmush qurmagan'), ('ajrashgan', 'Ajrashgan')], default='turmush_qurmagan', max_length=56, verbose_name='Oilaviy holati')),
                ('pregnancy_status', models.BooleanField(default=False, verbose_name='Homiladorlik holati')),
                ('number_of_children', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Bolalar soni')),
                ('disability_status', models.BooleanField(default=False, verbose_name='Nogironlik holati')),
                ('disability_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nogironlik turi')),
                ('orphan_status', models.CharField(choices=[('chin_yetim', 'Chin yetim'), ('yarim_yetim', 'Yarim yetim'), ('yetim_emas', 'Yetim emas')], default='yetim_emas', max_length=56, verbose_name='Yetim holati')),
                ('parentless_status', models.BooleanField(default=False, verbose_name="Ota-ona qaramog'idan mahrum")),
                ('social_registry_status', models.BooleanField(default=False, verbose_name="Ijtimoiy ro'yxatda")),
                ('ethics_status', models.CharField(choices=[('qizil', 'Qizil'), ('sariq', 'Sariq'), ('yashil', 'Yashil')], default='yashil', max_length=56, verbose_name='Axloqi')),
                ('special_status', models.BooleanField(default=False, verbose_name='Imtiyozli talaba')),
                ('special_status_description', models.TextField(blank=True, null=True, verbose_name='Imtiyoz tavsifi')),
                ('lens_document', models.FileField(blank=True, null=True, upload_to='documents/lens/', verbose_name='Obyektivka')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Izohlar')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='girl_details', to='student.student', verbose_name='Talaba')),
            ],
            options={
                'verbose_name': "Qiz talaba ma'lumotlari",
                'verbose_name_plural': "Qiz talabalar ma'lumotlari",
            },
        ),
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=56, verbose_name='Guruh nomi')),
                ('group_code', models.CharField(max_length=56, unique=True, verbose_name='Guruh kodi')),
                ('group_faculty', models.CharField(max_length=56, verbose_name='Fakultet')),
                ('group_level', models.CharField(max_length=56, verbose_name='Kurs')),
                ('group_year', models.CharField(max_length=56, verbose_name="O'quv yili")),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('students', models.ManyToManyField(blank=True, related_name='student_groups', to='student.student')),
            ],
            options={
                'verbose_name': 'Guruh',
                'verbose_name_plural': 'Guruhlar',
                'ordering': ['group_name'],
            },
        ),
    ]
