# Generated by Django 5.2.8 on 2026-01-27 12:28

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='education_type',
            field=models.CharField(default=datetime.datetime(2026, 1, 27, 12, 27, 17, 82397, tzinfo=datetime.timezone.utc), max_length=86, verbose_name="ta'lim-turi"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(default=django.utils.timezone.now, max_length=56, verbose_name='jinsi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='semester',
            field=models.CharField(default=1, max_length=56, verbose_name='semestr'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='education_form',
            field=models.CharField(default=1, max_length=56, verbose_name="Ta'lim shakli"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='education_lang',
            field=models.CharField(default=3125123, max_length=56, verbose_name="Ta'lim tili"),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='studentgroup',
            name='students',
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='students',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='student_groups', to='student.student'),
            preserve_default=False,
        ),
    ]
