# Generated by Django 5.2.8 on 2026-01-28 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_education_type_student_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentgroup',
            name='students',
        ),
        migrations.AddField(
            model_name='student',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='student.studentgroup'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_imeg',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='rasm'),
        ),
    ]
