# Generated by Django 5.2.8 on 2026-02-03 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_hemis_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='avg_gpa',
            field=models.CharField(max_length=255, verbose_name='Gpa-bali'),
        ),
        migrations.AlterField(
            model_name='student',
            name='education_type',
            field=models.CharField(max_length=255, verbose_name="ta'lim-turi"),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.CharField(max_length=255, verbose_name='email manzili'),
        ),
        migrations.AlterField(
            model_name='student',
            name='faculty',
            field=models.CharField(max_length=255, verbose_name='fakultet'),
        ),
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(max_length=255, verbose_name='kurs'),
        ),
        migrations.AlterField(
            model_name='student',
            name='paymentForm',
            field=models.CharField(max_length=255, verbose_name="to'lov shakli"),
        ),
        migrations.AlterField(
            model_name='student',
            name='studentStatus',
            field=models.CharField(max_length=255, verbose_name='talaba-holati'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Talaba_Ismi'),
        ),
        migrations.AlterField(
            model_name='studentgirls',
            name='disability_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nogironlik turi'),
        ),
        migrations.AlterField(
            model_name='studentgirls',
            name='ethics_status',
            field=models.CharField(choices=[('qizil', 'Qizil'), ('sariq', 'Sariq'), ('yashil', 'Yashil')], default='yashil', max_length=256, verbose_name='Axloqi'),
        ),
        migrations.AlterField(
            model_name='studentgirls',
            name='orphan_status',
            field=models.CharField(choices=[('chin_yetim', 'Chin yetim'), ('yarim_yetim', 'Yarim yetim'), ('yetim_emas', 'Yetim emas')], default='yetim_emas', max_length=256, verbose_name='Yetim holati'),
        ),
        migrations.AlterField(
            model_name='studentgirls',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=560, null=True, verbose_name="Tug'ilgan joyi"),
        ),
    ]
