# Generated by Django 5.2.8 on 2026-04-10 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_student_avg_gpa_alter_student_education_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(blank=True, max_length=112, null=True, verbose_name='Telfon-raqam'),
        ),
        migrations.AlterField(
            model_name='studentgirls',
            name='current_address',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Hozirgi manzili'),
        ),
        migrations.AlterField(
            model_name='studentgirls',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name="Tug'ilgan joyi"),
        ),
        migrations.AlterField(
            model_name='studentgroup',
            name='education_form',
            field=models.CharField(max_length=112, verbose_name="Ta'lim shakli"),
        ),
        migrations.AlterField(
            model_name='studentgroup',
            name='education_lang',
            field=models.CharField(max_length=112, verbose_name="Ta'lim tili"),
        ),
        migrations.AlterField(
            model_name='studentgroup',
            name='group_code',
            field=models.CharField(max_length=112, unique=True, verbose_name='Guruh kodi'),
        ),
        migrations.AlterField(
            model_name='studentgroup',
            name='group_faculty',
            field=models.CharField(max_length=112, verbose_name='Fakultet'),
        ),
        migrations.AlterField(
            model_name='studentgroup',
            name='group_level',
            field=models.CharField(max_length=112, verbose_name='Kurs'),
        ),
        migrations.AlterField(
            model_name='studentgroup',
            name='group_name',
            field=models.CharField(max_length=112, verbose_name='Guruh nomi'),
        ),
        migrations.AlterField(
            model_name='studentgroup',
            name='group_year',
            field=models.CharField(max_length=112, verbose_name="O'quv yili"),
        ),
    ]
