# Generated by Django 5.2.8 on 2026-01-28 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_remove_studentgroup_students_student_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgirls',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tuman'),
        ),
        migrations.AddField(
            model_name='studentgirls',
            name='province',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Viloyat'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_imeg',
            field=models.URLField(blank=True, null=True),
        ),
    ]
