# Generated by Django 5.2.8 on 2026-09-22

from datetime import datetime, timezone
from decimal import Decimal, InvalidOperation

from django.db import migrations, models


def _normalize_birth_date(value):
    if value in (None, ''):
        return None

    raw_value = str(value).strip()
    if raw_value.isdigit():
        timestamp = int(raw_value)
        if timestamp > 10**11:
            timestamp //= 1000
        try:
            return datetime.fromtimestamp(timestamp, tz=timezone.utc).date().isoformat()
        except (OverflowError, OSError, ValueError):
            return None

    for date_format in ('%Y-%m-%d', '%d-%m-%Y', '%d.%m.%Y'):
        try:
            return datetime.strptime(raw_value, date_format).date().isoformat()
        except ValueError:
            continue

    try:
        return datetime.fromisoformat(raw_value.replace('Z', '+00:00')).date().isoformat()
    except ValueError:
        return None


def _normalize_gpa(value):
    if value in (None, ''):
        return None
    try:
        return str(Decimal(str(value)).quantize(Decimal('0.01')))
    except (InvalidOperation, ValueError, TypeError):
        return None


def forwards(apps, schema_editor):
    Student = apps.get_model('student', 'Student')
    records = list(
        Student.objects.values('pk', 'hemis_id', 'student_id_number', 'birth_date', 'avg_gpa')
    )

    # Old callback semantics were inverted: hemis_id contained the student
    # number and student_id_number contained data.id. Clear the unique field
    # first so the swap is safe even when databases enforce uniqueness eagerly.
    Student.objects.all().update(student_id_number=None)

    for record in records:
        old_student_number = str(record['hemis_id']).strip() if record['hemis_id'] else ''
        old_hemis_id = str(record['student_id_number']).strip() if record['student_id_number'] else ''
        new_hemis_id = old_hemis_id or old_student_number or str(record['pk'])
        new_student_number = old_student_number or None

        Student.objects.filter(pk=record['pk']).update(
            hemis_id=new_hemis_id,
            student_id_number=new_student_number,
            birth_date=_normalize_birth_date(record['birth_date']),
            avg_gpa=_normalize_gpa(record['avg_gpa']),
        )


def backwards(apps, schema_editor):
    Student = apps.get_model('student', 'Student')
    records = list(
        Student.objects.values('pk', 'hemis_id', 'student_id_number', 'birth_date', 'avg_gpa')
    )
    Student.objects.all().update(student_id_number=None)

    for record in records:
        canonical_hemis_id = str(record['hemis_id']).strip() if record['hemis_id'] else ''
        canonical_student_number = (
            str(record['student_id_number']).strip()
            if record['student_id_number'] else ''
        )
        birth_date = record['birth_date']
        avg_gpa = record['avg_gpa']

        Student.objects.filter(pk=record['pk']).update(
            hemis_id=canonical_student_number or canonical_hemis_id,
            student_id_number=canonical_hemis_id or None,
            birth_date=birth_date.isoformat() if birth_date else None,
            avg_gpa=str(avg_gpa) if avg_gpa is not None else None,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_student_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='hemis_extra',
            field=models.JSONField(blank=True, default=dict, verbose_name="HEMIS qo'shimcha ma'lumotlari"),
        ),
        migrations.AddField(
            model_name='student',
            name='hemis_login',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='HEMIS login'),
        ),
        migrations.AddField(
            model_name='student',
            name='hemis_synced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="HEMIS bilan oxirgi sinxronizatsiya"),
        ),
        migrations.AddField(
            model_name='student',
            name='hemis_uuid',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='HEMIS UUID'),
        ),
        migrations.RenameField(
            model_name='student',
            old_name='student_imeg',
            new_name='student_image_url',
        ),
        migrations.AlterField(
            model_name='student',
            name='student_image_url',
            field=models.URLField(blank=True, null=True, verbose_name='Profil rasmi'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id_number',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='Talaba ID raqami'),
        ),
        migrations.RunPython(forwards, backwards),
        migrations.AlterField(
            model_name='student',
            name='hemis_id',
            field=models.CharField(max_length=64, unique=True, verbose_name='HEMIS ID'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email manzili'),
        ),
        migrations.AlterField(
            model_name='student',
            name='passport_number',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Passport raqami'),
        ),
        migrations.AlterField(
            model_name='student',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name="Tug'ilgan sana"),
        ),
        migrations.AlterField(
            model_name='student',
            name='avg_gpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='GPA bali'),
        ),
    ]
