# Generated by Django 5.2.8 on 2026-01-20 13:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_name', models.CharField(blank=True, max_length=56, null=True, verbose_name='Talaba_Ismi')),
                ('phone_number', models.CharField(blank=True, max_length=56, null=True, verbose_name='Telfon-raqam')),
                ('student_imeg', models.ImageField(upload_to='media/', verbose_name='rasm')),
                ('student_id_number', models.CharField(blank=True, max_length=16, null=True, unique=True)),
                ('email', models.CharField(max_length=86)),
                ('passport_number', models.CharField(max_length=12, verbose_name='passport raqami')),
                ('birth_date', models.CharField(max_length=50, verbose_name="Tug'ilgan-kun-sanasi")),
                ('groups', models.JSONField()),
                ('studentStatus', models.CharField(max_length=86, verbose_name='talaba-holati')),
                ('paymentForm', models.CharField(max_length=86, verbose_name="to'lov shakli")),
                ('faculty', models.CharField(max_length=86, verbose_name='fakultet')),
                ('level', models.CharField(max_length=86, verbose_name='kurs')),
                ('avg_gpa', models.CharField(max_length=86, verbose_name='Gpa-bali')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentGirls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_of_birth', models.CharField(max_length=100, verbose_name="Tug'ilgan joyi")),
                ('current_address', models.CharField(max_length=256, verbose_name='Hozirgi manzili')),
                ('marital_status', models.CharField(max_length=56, verbose_name='Oilaviy holati')),
                ('pregancy_status', models.CharField(max_length=56, verbose_name='Homiladorlik holati')),
                ('number_of_children', models.CharField(max_length=56, verbose_name='Bolalar soni')),
                ('disability_status', models.CharField(max_length=56, verbose_name='Nogironlik holati')),
                ('orphan_status', models.CharField(choices=[(1, 'Yarim'), (2, 'Yetim')], max_length=56, verbose_name='Yetim holati')),
                ('parentless_status', models.CharField(max_length=56, verbose_name='Ota-ona qaramog’idan mahrum bo’lganlar')),
                ('social_registry_status', models.CharField(max_length=56, verbose_name='Ijtimoiy ro’yxatda turadigan (ayollar daftari)')),
                ('ethics_status', models.CharField(choices=[(1, 'Sariq')], max_length=56, verbose_name='Axloqi')),
                ('special_status', models.CharField(max_length=56, verbose_name='Imtiyoz bilan talaba bo’lganlar')),
                ('lens', models.FileField(upload_to='media/', verbose_name='Obyektivka')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=56, verbose_name='Guruh nomi')),
                ('group_code', models.CharField(max_length=56, verbose_name='Guruh kodi')),
                ('group_faculty', models.CharField(max_length=56, verbose_name='Guruh fakulteti')),
                ('group_level', models.CharField(max_length=56, verbose_name='Guruh kursi')),
                ('group_year', models.CharField(max_length=56, verbose_name='Guruh yili')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('student', models.ManyToManyField(related_name='student_groups', to='user.student')),
            ],
        ),
    ]
